### ISSUE TITLE
[Refactor] 장바구니 목록 조회 기능 수정

### ISSUE THREAD

**Issue by JeYeongR** [JeYeongR/credit-market-BE-Refactoring#1]
## Description

장바구니 목록 조회 기능 수정

## Tasks(Process)
- [x] Controller 리턴 수정
- [x] CartResponseDTO 수정 
- [x] 필요없는 Service 로직 제거 및 수정
- [x] checkedFavorite 메서드 수정

## References
- [ResponseEntity](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/ResponseEntity.html)
