### ISSUE TITLE
[Refactor] 관심 상품 추가, 삭제 기능 수정

### ISSUE THREAD

**Issue by JeYeongR** [JeYeongR/credit-market-BE-Refactoring#16]
## Description

관심 상품 추가 기능과 삭제 API 통합

## Tasks(Process)
- [x] 관심 상품 RequestDTO 추가
- [x] 관심 상품 추가 기능과 삭제 API 통합
- [x] 관심 상품 Controller 파라미터, 리턴 값 수정
- [x] 관심 상품 추가 Service 수정
