### ISSUE TITLE
[Refactor] 관심 상품 목록 조회 기능 수정

### ISSUE THREAD

**Issue by JeYeongR** [JeYeongR/credit-market-BE-Refactoring#18]
## Description

관심 상품 목록 조회 기능 수정

## Tasks(Process)
- [x] Controller 파라미터, 리턴값 수정
- [x] 쿼리 메서드 변경
- [x] Service 로직 변경
