### ISSUE TITLE
[Refactor] 상품 구매 기능 수정

### ISSUE THREAD

**Issue by JeYeongR** [JeYeongR/credit-market-BE-Refactoring#24]
## Description

상품 구매 기능 수정

## Tasks(Process)
- [x] Controller DTO 변경
- [x] Controller 리턴값 변경
- [x] Service 로직 수정
