### ISSUE TITLE
[Refactor] 상품 목록 조회 기능 수정

### ISSUE THREAD

**Issue by JeYeongR** [JeYeongR/credit-market-BE-Refactoring#26]
## Description

상품 목록 조회 기능 수정

## Tasks(Process)
- [x] Controller 리턴 수정
- [x] Repository 쿼리 메서드 수정
- [x] Service 로직 변경
